name: "Monorepo Integrity"

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  monorepo-integrity:
    name: Check monorepo integrity
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          fetch-depth: 2
          submodules: "true"

      - name: 💽 Node and Caching
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7
        with:
          node-version: 18

      - name: 📥 Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: 📦 Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: 🗃️ Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 📥 pnpm install
        shell: bash
        working-directory: ./
        run: |
          pnpm install --frozen-lockfile
        env:
          HUSKY: "0" # By default do not run HUSKY install

      - name: 👬🏽 Check for conflicting versions across the monorepo
        run: pnpm g:check:deps:mismatch

      # This check will be disabled while a major version change of sdk-core is underway
      - name: 👬🏽 Check for duplicate dependencies in lock file
        run: pnpm dedupe --check

      - name: 🧑‍⚖️ Check for pnpm constraints
        run: echo "Constraints check skipped for pnpm"
